# Configuração para o Nixpacks

# Define o diretório raiz do projeto
[build]
base = "./backend"

[phases.setup]
cmds = [
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "npm run start:prod"

[build.environment]
NODE_VERSION = "18.x"
NPM_VERSION = "9.x"

[build.args]
NIXPACKS_NODE_VERSION = "18"

[build.prebuild]
cmds = [
    "echo 'Running prebuild commands...'"
]

[build.postbuild]
cmds = [
    "echo 'Build completed successfully!'"
]

# Define os diretórios que contêm os arquivos do projeto
[build.include]
paths = [
    "**/*"
]

# Define os arquivos que devem ser ignorados
[build.exclude]
paths = [
    "node_modules",
    ".git",
    ".github",
    "dist",
    "build",
    "*.log",
    "*.tmp"
]
