[build]
builder = "nixpacks"
root = "./backend"

[build.requires]
node = "18.x"

[build.build_command]
command = "npm install && npm run build"

[build.start_command]
command = "npm run start:prod"

[deploy]
start_command = "npm run start:prod"
restart_policy = "on-failure"
restart_attempts = 10

[deploy.checks]
enabled = true
timeout = 180
interval = 30
start_period = 10
