[build]
builder = "nixpacks"

[build.requires]
node = "18.x"

[build.build_command]
command = "cd backend && npm install && npm run build"

[build.start_command]
command = "cd backend && npm start"

[deploy]
start_command = "cd backend && npm start"
restart_policy = "on-failure"
restart_attempts = 10

[deploy.checks]
enabled = true
timeout = 180
interval = 30
start_period = 10
