services:
  app:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/comandas
    depends_on:
      - db

  db:
    image: postgres:13  # Use the official PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: comandas
    ports:
      - "5432:5432"  # Map port 5432 of the container to port 5432 on the host
