# Estágio de construção
FROM node:16 AS builder

WORKDIR /usr/src/app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante dos arquivos
COPY . .

# Compilar TypeScript
RUN npm run build

# Estágio de produção
FROM node:16-slim

WORKDIR /usr/src/app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar apenas as dependências de produção
RUN npm install --only=production

# Copiar os arquivos compilados do estágio de construção
COPY --from=builder /usr/src/app/dist ./dist

# Expor a porta
EXPOSE 5000

# Comando para iniciar a aplicação
CMD ["node", "dist/server.js"]